######################## default configuration ####################
baseURL = '/'
languageCode = 'ru'
title = 'Torya - роспись, барельеф, аэрография | Hugo Site'
theme = "torya"

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
  [[params.plugins.css]]
  link = "https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css"
  [[params.plugins.css]]
  link = "https://embed.typeform.com/next/css/widget.css"
  [[params.plugins.css]]
  link = "plugins/css/bootstrap.min.css"
  [[params.plugins.css]]
  link = "plugins/css/Lightbox-Gallery.css"
  [[params.plugins.css]]
  link = "plugins/css/grid-gallery.min.css"
  [[params.plugins.css]]
  link = "plugins/css/Bold-BS4-Header-with-HTML5-Video-Background.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
  [[params.plugins.js]]
  link = "https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js"
  [[params.plugins.js]]
  link = "plugins/js/grayscale.js"
  [[params.plugins.js]]
  link = "plugins/js/Lightbox-Gallery.js"
  [[params.plugins.js]]
  link = "https://embed.typeform.com/next/embed.js"
  [[params.plugins.js]]
  link = "plugins/js/script.min.js"

#################### default parameters ################################
[params]
yandexMetrika = "84271363"
yandexVerification = "073b0fab8d84d1e1"

twitterDescription = "Добавляю жизни на поверхности. Рисую на автомобилях, стенах, холстах. Индивидуально. С душой."
twitterImage = "images/portfolio/9-image.jpg"
twitterCard = "summary_large_image"
twitterTitle = "Роспись стен, барельеф, аэрография"

ogImage = "images/portfolio/9-image.jpg"

navbarBrand = "Torya.art"
copyright = "Copyright &copy;&nbsp;Torya 2022"

#################### cover parameters ################################
[params.cover]
  [params.cover.poster]
  link = "images/cover.png"
  [params.cover.title]
  text = "рисую"
  [[params.cover.thesis]]
  text = "Делаю любые поверхности ярче"
  [[params.cover.thesis]]
  text = "Роспись, барельеф, аэрография, картины"
  [[params.cover.video]]
  link = "https://torya.art/torya.art.background.mp4"
  type = "video/mp4"
  [[params.cover.video]]
  link = "https://torya.art/torya.art.background.new.webm"
  type = "video/webm"

############################## navigation ###############################
[menu]

  [[menu.main]]
  name = "Работы"
  URL = "#portfolio"
  weight = 1

  [[menu.main]]
  name = "Связаться"
  URL = "#contact"
  weight = 2

  [[menu.main]]
  name = "История"
  URL = "#about"
  weight = 3


############################## social ###############################
[social]
  instagram = "torya.art"
  zen = "6122ad20349c522b4deb02d9"
  whatsapp = "79210245752"
  whatsapptxt = "Рисуете?"
  email = "hello@torya.art"
  youtube = "channel/UCW0n0GlCznwJX_JzLmTRaTQ"

